// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vagu_block.h for the primary calling header

#ifndef _Vagu_block_lru_single0__I3_H_
#define _Vagu_block_lru_single0__I3_H_

#include "verilated_heavy.h"
#include "verilated_threads.h"

class Vagu_block__Syms;

//----------

VL_MODULE(Vagu_block_lru_single0__I3) {
  public:
    
    // PORTS
    // Begin mtask footprint all: 9 30 31 32 33 34 35 36 37 
    VL_OUT8(newLRU__en,2,0);
    // Begin mtask footprint all: 
    VL_IN8(__PVT__lru,2,0);
    VL_IN8(__PVT__newLRU,2,0);
    VL_IN8(__PVT__hitLRU,2,0);
    VL_IN8(__PVT__init,0,0);
    VL_IN8(__PVT__en,0,0);
    VL_OUT8(newLRU__out,2,0);
    
    // LOCAL SIGNALS
    // Begin mtask footprint all: 1 7 14 15 16 18 19 25 26 27 
    VL_SIG8(__PVT__adders_gen__DOT__inc_mod__DOT__nP1,2,0);
    VL_SIG8(__PVT__adders_gen__DOT__inc_mod__DOT__P2,2,0);
    // Begin mtask footprint all: 1 7 14 15 18 19 25 26 27 28 
    VL_SIG8(__PVT__adders_gen__DOT__cmp_mod__DOT__P1,2,0);
    VL_SIG8(__PVT__adders_gen__DOT__cmp_mod__DOT__G1,2,0);
    // Begin mtask footprint all: 7 14 15 18 25 26 27 28 
    VL_SIG8(__PVT__adders_gen__DOT__cmp_mod__DOT__nP2,2,0);
    VL_SIG8(__PVT__adders_gen__DOT__cmp_mod__DOT__nG2,2,0);
    // Begin mtask footprint all: 7 14 15 17 18 25 26 27 28 29 30 31 33 34 36 
    VL_SIG8(__PVT__adders_gen__DOT__cmp_mod__DOT__C,2,0);
    // Begin mtask footprint all: 7 14 15 17 25 26 27 28 29 30 31 33 36 
    VL_SIG8(__PVT__hitAfter,0,0);
    
    // LOCAL VARIABLES
    // Begin mtask footprint all: 17 30 31 33 36 
    VL_SIG8(adders_gen__DOT__inc_mod__DOT__out__out__out0,2,0);
    // Begin mtask footprint all: 15 16 17 25 26 27 30 31 33 36 
    VL_SIG8(adders_gen__DOT__inc_mod__DOT__out__out__out1,2,0);
    // Begin mtask footprint all: 7 14 15 16 17 25 26 27 30 31 33 36 
    VL_SIG8(adders_gen__DOT__inc_mod__DOT__out__out__out2,2,0);
    VL_SIG8(adders_gen__DOT__inc_mod__DOT__out__out__out3,2,0);
    VL_SIG8(adders_gen__DOT__inc_mod__DOT__out__out__out4,2,0);
    VL_SIG8(adders_gen__DOT__inc_mod__DOT__out__out__out5,2,0);
    // Begin mtask footprint all: 7 14 15 16 17 19 25 27 28 30 31 33 34 35 36 
    VL_SIG8(newLRU__out__en5,2,0);
    // Begin mtask footprint all: 7 14 15 16 17 25 26 27 28 29 30 31 33 34 36 
    VL_SIG8(__pinNumber2__en0,2,0);
    // Begin mtask footprint all: 7 14 15 17 25 26 27 28 29 30 31 33 34 35 36 
    VL_SIG8(newLRU__out__en2,2,0);
    // Begin mtask footprint all: 7 14 17 26 29 30 31 33 34 35 36 
    VL_SIG8(newLRU__out__en3,2,0);
    
    // INTERNAL VARIABLES
  private:
    Vagu_block__Syms* __VlSymsp;  // Symbol table
  public:
    
    // PARAMETERS
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vagu_block_lru_single0__I3);  ///< Copying not allowed
  public:
    Vagu_block_lru_single0__I3(const char* name = "TOP");
    ~Vagu_block_lru_single0__I3();
    
    // API METHODS
    
    // INTERNAL METHODS
    void __Vconfigure(Vagu_block__Syms* symsp, bool first);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _sequent__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__769(Vagu_block__Syms* __restrict vlSymsp);
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__123(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__171(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__195(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__242(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__465(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__633(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__681(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__729(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__75(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__243(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__284(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__586(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__634(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__730(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__244(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__285(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__635(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__731(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__245(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__286(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__636(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__732(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__246(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__287(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__637(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__733(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__247(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__288(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__638(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__734(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__248(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__289(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__639(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__735(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__290(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__640(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu2_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__736(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__1(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__115(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__163(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__187(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__235(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__319(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__409(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__457(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__505(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__55(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__577(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__61(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__625(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__67(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__673(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__721(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__236(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__277(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__367(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__410(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__506(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__578(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__626(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__722(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__237(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__278(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__627(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__723(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__238(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__279(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__628(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__724(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__239(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__280(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__629(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__725(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__240(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__281(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__630(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__726(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__241(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__282(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__631(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__727(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__283(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__416(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__49(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__512(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__632(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__Wagu_mod__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__728(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__131(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__203(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__249(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__473(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__553(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__641(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__689(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__737(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__83(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__250(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__291(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__594(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__642(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__738(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__251(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__292(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__643(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__739(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__252(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__293(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__644(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__740(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__253(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__294(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__645(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__741(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__254(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__295(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__646(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__742(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__255(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__296(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__647(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__743(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__297(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__648(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu0__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__744(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__147(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__219(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__263(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__489(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__569(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__657(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__705(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__753(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__99(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__264(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__305(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__610(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__658(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__754(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__265(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__306(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__659(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__755(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__266(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__307(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__660(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__756(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__267(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__308(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__661(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__757(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__268(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__309(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__662(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__758(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__269(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__310(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__663(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__759(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__311(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__664(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu1__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__760(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__139(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__211(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__256(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__481(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__561(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__649(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__697(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__745(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__91(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__257(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__298(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__602(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__650(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__746(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__258(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__299(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__651(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__747(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__259(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__300(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__652(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__748(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__260(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__301(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__653(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__749(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__261(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__302(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__654(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__750(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__262(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__303(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__655(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__751(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__304(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__656(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__agu2__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__752(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__107(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__155(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__179(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__227(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__270(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__497(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__665(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__713(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__0__KET____DOT__lru_mod__761(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__271(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__312(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__618(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__666(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__1__KET____DOT__lru_mod__762(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__272(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__313(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__667(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__2__KET____DOT__lru_mod__763(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__273(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__314(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__668(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__3__KET____DOT__lru_mod__764(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__274(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__315(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__669(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__4__KET____DOT__lru_mod__765(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__275(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__316(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__670(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__5__KET____DOT__lru_mod__766(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__276(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__317(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__671(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__6__KET____DOT__lru_mod__767(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__318(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__672(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__agu_block__DOT__rec_agu_mod__DOT__tlb_mod__ways_gen__BRA__3__KET____DOT__lru_mod__DOT__lru_gen__BRA__7__KET____DOT__lru_mod__768(Vagu_block__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(128);

#endif // guard
