module money_pt(
  clk, rst,
  wr0_hit,
  wr0_l1miss,
  wr0_addrE,
  wr0_addrO,
  wr0_banks, 
  wr0_begin,.wr0_end,
  wr0_bgn_ben,wr0_end_ben,
  wr0_odd,wr0_split,
  wr0_data,
  wr0_pbit,
  wr0_d128,
  wr1_hit,
  wr1_l1miss,
  wr1_addrE, 
  wr1_addrO,
  wr1_banks, 
  wr1_begin,wr1_end,
  wr1_bgn_ben,wr1_end_ben,
  wr1_odd,wr1_split,
  wr1_data,
  wr1_pbit,
  wr1_d128,
  Din_en,Din_data,
  Dout_en,
  wrstall);
endmodule
