// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfu_alu.h for the primary calling header

#ifndef _Vfu_alu_alu_H_
#define _Vfu_alu_alu_H_

#include "verilated.h"

class Vfu_alu__Syms;

//----------

VL_MODULE(Vfu_alu_alu) {
  public:
    
    // PORTS
    VL_IN8(clk,0,0);
    VL_IN8(rst,0,0);
    VL_IN8(except,0,0);
    VL_IN8(except_thread,0,0);
    VL_IN8(thread,0,0);
    VL_IN8(dataEn,0,0);
    VL_IN8(nDataAlt,0,0);
    VL_IN8(retEn,0,0);
    VL_IN8(valS,5,0);
    VL_OUT8(retEn__out,0,0);
    VL_OUT8(retEn__en,0,0);
    VL_IN16(operation,12,0);
    VL_IN16(retData,8,0);
    VL_OUT16(retData__out,8,0);
    VL_OUT16(retData__en,8,0);
    VL_INW(val1,64,0,3);
    VL_INW(val2,64,0,3);
    VL_INW(valRes,64,0,3);
    VL_OUTW(valRes__out,64,0,3);
    VL_OUTW(valRes__en,64,0,3);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__flag8_ZF;
        CData/*0:0*/ __PVT__flag8_SF;
        CData/*0:0*/ __PVT__flagAdd8_CF;
        CData/*0:0*/ __PVT__flagAdd8_AF;
        CData/*0:0*/ __PVT__carryAdd16;
        CData/*0:0*/ __PVT__carryAdd8LL;
        CData/*0:0*/ __PVT__carryAdd8HL;
        CData/*0:0*/ __PVT__carryAdd8LH;
        CData/*0:0*/ __PVT__carryAdd8HH;
        CData/*0:0*/ __PVT__carryAdd4HL;
        CData/*0:0*/ __PVT__carryAdd64_reg;
        CData/*0:0*/ __PVT__carryAdd32_reg;
        CData/*0:0*/ __PVT__carryAdd16_reg;
        CData/*0:0*/ __PVT__carryAdd8LL_reg;
        CData/*0:0*/ __PVT__carryAdd8HL_reg;
        CData/*0:0*/ __PVT__carryAdd8LH_reg;
        CData/*0:0*/ __PVT__carryAdd8HH_reg;
        CData/*0:0*/ __PVT__carryAdd4LL_reg;
        CData/*0:0*/ __PVT__carryAdd4HL_reg;
        CData/*0:0*/ __PVT__carryAdd4HH_reg;
        CData/*0:0*/ __PVT__val1_sign64;
        CData/*0:0*/ __PVT__val1_sign32;
        CData/*0:0*/ __PVT__val1_sign16;
        CData/*0:0*/ __PVT__val1_sign8;
        CData/*0:0*/ __PVT__val2_sign64;
        CData/*0:0*/ __PVT__val2_sign32;
        CData/*0:0*/ __PVT__val2_sign16;
        CData/*0:0*/ __PVT__val2_sign8;
        CData/*0:0*/ __PVT__flagAdd64_OF;
        CData/*0:0*/ __PVT__flagAdd32_OF;
        CData/*0:0*/ __PVT__flagAdd16_OF;
        CData/*0:0*/ __PVT__flagAdd8_OF;
        CData/*0:0*/ __PVT__flagSub64_OF;
        CData/*0:0*/ __PVT__flagSub32_OF;
        CData/*0:0*/ __PVT__flagSub16_OF;
        CData/*0:0*/ __PVT__flagSub8_OF;
        CData/*5:0*/ __PVT__flags_COASZP;
        CData/*0:0*/ __PVT__isFlags_reg;
        CData/*0:0*/ __PVT__nDataAlt_reg;
        CData/*3:0*/ __PVT__val1One;
        CData/*3:0*/ __PVT__val1One_reg;
        CData/*4:0*/ __PVT__jumpType;
        CData/*0:0*/ __PVT__doJmp;
        CData/*0:0*/ __PVT__add_en;
        CData/*0:0*/ __PVT__shift_en;
        CData/*0:0*/ __PVT__sahf_en;
        CData/*5:0*/ __PVT__valS_reg;
        CData/*5:0*/ __PVT__val1_reg;
        CData/*0:0*/ __PVT__dataEn_reg;
        CData/*0:0*/ __PVT__thrinh_reg;
        CData/*0:0*/ __PVT__except_reg;
        CData/*0:0*/ __PVT__except_thread_reg;
        CData/*0:0*/ __PVT__logic_en;
        CData/*0:0*/ __PVT__cmov_en;
        CData/*2:0*/ __PVT__cin_seq;
        CData/*0:0*/ __PVT__cin_seq_reg;
        CData/*0:0*/ __PVT__is_ptr;
        CData/*0:0*/ __PVT__is_sub;
        CData/*0:0*/ __PVT__is_ptr_reg;
        CData/*1:0*/ __PVT__mainAdder_mod__DOT__pos_ack;
        CData/*1:0*/ __PVT__mainAdder_mod__DOT__neg_ack;
        CData/*1:0*/ __PVT__mainAdder_mod__DOT__pos_flip;
        CData/*1:0*/ __PVT__mainAdder_mod__DOT__neg_flip;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__cout_sec0;
    };
    struct {
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__is_ptr;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__err;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__posx;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__do_pos;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__do_pos2;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__do_neg;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__do_neg2;
        CData/*0:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__do_neg1;
        CData/*7:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__msk;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__pos0;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__pos2;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__neg2;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__neg1;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__neg0;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__xpos0;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__xpos2;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__xneg2;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__xneg1;
        CData/*3:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__xneg0;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__nP0;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__nG0;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__P1;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__G1;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__nP2;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__nG2;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__P3;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__G3;
        CData/*6:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__cmp_mod__DOT__nC;
        SData/*12:0*/ __PVT__retOp;
        WData/*64:0*/ __PVT__valRes_reg[3];
        IData/*31:0*/ __PVT__mainAdder_mod__DOT__nih_mod__DOT__mask;
        QData/*63:0*/ __PVT__valRes1;
        QData/*63:0*/ __PVT__val_and;
        QData/*63:0*/ __PVT__val_or;
        QData/*63:0*/ __PVT__val_xor;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nP0;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nG0;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__P1;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__G1;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nP2;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nG2;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__P3;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__G3;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nP4;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nG4;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__P5;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__G5;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nP6;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nG6;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__C;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__X;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nX;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__C1;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__nC1;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__xb;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__bitEn;
        QData/*39:0*/ __PVT__mainAdder_mod__DOT__unptr;
        QData/*63:0*/ __PVT__mainAdder_mod__DOT__ptr;
        QData/*40:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__O;
        QData/*40:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__X;
        QData/*40:0*/ __PVT__mainAdder_mod__DOT__hin_mod__DOT__And;
    };
    
    // LOCAL VARIABLES
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*1:0*/ __Vcellinp__mainAdder_mod__ben;
        CData/*5:0*/ flags_COASZP__en58;
        CData/*5:0*/ flags_COASZP__en59;
        CData/*5:0*/ flags_COASZP__en60;
        CData/*5:0*/ flags_COASZP__en61;
        CData/*5:0*/ flags_COASZP__en62;
        CData/*5:0*/ flags_COASZP__en63;
        CData/*5:0*/ flags_COASZP__en64;
        CData/*5:0*/ flags_COASZP__en65;
        CData/*5:0*/ flags_COASZP__en66;
        CData/*5:0*/ flags_COASZP__en67;
        CData/*5:0*/ flags_COASZP__en68;
        CData/*5:0*/ flags_COASZP__en69;
        CData/*5:0*/ flags_COASZP__en70;
        CData/*5:0*/ flags_COASZP__en71;
        CData/*5:0*/ flags_COASZP__en72;
        CData/*5:0*/ flags_COASZP__en73;
        CData/*5:0*/ flags_COASZP__en74;
        CData/*5:0*/ flags_COASZP__en75;
        CData/*5:0*/ flags_COASZP__en76;
        CData/*5:0*/ flags_COASZP__en77;
        CData/*5:0*/ flags_COASZP__en78;
        CData/*5:0*/ flags_COASZP__en79;
        CData/*5:0*/ flags_COASZP__en80;
        CData/*5:0*/ flags_COASZP__en81;
        CData/*5:0*/ flags_COASZP__en83;
        CData/*5:0*/ flags_COASZP__en85;
        CData/*5:0*/ flags_COASZP__en86;
        SData/*8:0*/ retData__out__out1;
        SData/*8:0*/ retData__out__en1;
        SData/*8:0*/ retData__out__out2;
        SData/*8:0*/ retData__out__en2;
        SData/*8:0*/ retData__out__out3;
        SData/*8:0*/ retData__out__en3;
        SData/*8:0*/ retData__out__out4;
        SData/*8:0*/ retData__out__en4;
        SData/*8:0*/ retData__out__out5;
        WData/*64:0*/ out__en0[3];
        WData/*64:0*/ valRes__out__out7[3];
        WData/*64:0*/ valRes__out__en8[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out0[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out1[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en1[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out2[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en2[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out3[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en3[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out4[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en4[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out5[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en5[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out6[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en6[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out7[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en7[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out8[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en8[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out9[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en9[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out10[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en10[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out11[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en11[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out12[3];
    };
    struct {
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en12[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out13[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en13[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out14[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en14[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out15[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en15[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out16[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en16[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out17[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en17[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out18[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en18[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out19[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en19[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out20[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en20[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out21[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en21[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out22[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en22[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out23[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en23[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out24[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en24[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out25[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en25[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out26[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en26[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out27[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en27[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out28[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en28[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out29[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en29[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out30[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en30[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out31[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en31[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out32[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en32[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out33[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en33[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out34[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en34[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out35[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en35[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out36[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en36[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out37[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en37[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out38[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en38[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out39[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en39[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out40[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en40[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out41[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en41[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out42[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en42[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out43[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en43[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out44[3];
    };
    struct {
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en44[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out45[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en45[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out46[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en46[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out47[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en47[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out48[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en48[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out49[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en49[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out50[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en50[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out51[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en51[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out52[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en52[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out53[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en53[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out54[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en54[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out55[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en55[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out56[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en56[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out57[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en57[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out58[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en58[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out59[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en59[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out60[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en60[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out61[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en61[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out62[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en62[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out63[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en63[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out64[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en64[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out65[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en65[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out66[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en66[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out67[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en67[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out68[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en68[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out69[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en69[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out70[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en70[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out71[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en71[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out72[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en72[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out73[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en73[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out74[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en74[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out75[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en75[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out76[3];
    };
    struct {
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en76[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out77[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en77[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out78[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en78[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out79[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en79[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out80[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en80[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out81[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en81[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out82[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en82[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out83[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en83[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out84[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en84[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out85[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en85[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out86[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en86[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out87[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en87[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out88[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en88[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out89[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en89[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out90[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en90[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out91[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en91[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out92[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en92[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out93[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en93[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out94[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en94[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out95[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en95[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out96[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en96[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out97[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en97[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out98[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en98[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out99[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en99[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out100[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en100[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out101[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en101[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out102[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en102[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out103[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en103[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out104[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en104[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out105[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en105[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out106[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en106[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out107[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en107[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out108[3];
    };
    struct {
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en108[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out109[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en109[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out110[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en110[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out111[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en111[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out112[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en112[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out113[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en113[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out114[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en114[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out115[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en115[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out116[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en116[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out117[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en117[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out118[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en118[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out119[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en119[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out120[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en120[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out121[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en121[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out122[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en122[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out123[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en123[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out124[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en124[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out125[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en125[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out126[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en126[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out127[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en127[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out128[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en128[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out129[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en129[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__out130[3];
        WData/*64:0*/ mainAdder_mod__DOT__out__out__en130[3];
        QData/*63:0*/ valRes1__en;
        QData/*63:0*/ valRes1__out11;
        QData/*63:0*/ valRes1__en11;
        QData/*63:0*/ valRes1__out12;
        QData/*63:0*/ valRes1__en12;
        QData/*63:0*/ valRes1__out13;
        QData/*63:0*/ valRes1__en13;
        QData/*63:0*/ valRes1__out14;
        QData/*63:0*/ valRes1__en14;
        QData/*63:0*/ valRes1__out15;
        QData/*63:0*/ valRes1__en15;
        QData/*63:0*/ valRes1__out16;
        QData/*63:0*/ valRes1__en16;
        QData/*63:0*/ valRes1__out17;
        QData/*63:0*/ valRes1__en17;
        QData/*63:0*/ valRes1__out18;
        QData/*63:0*/ valRes1__en18;
        QData/*63:0*/ valRes1__out19;
        QData/*63:0*/ valRes1__en19;
    };
    struct {
        QData/*63:0*/ valRes1__out20;
        QData/*63:0*/ valRes1__en20;
        QData/*63:0*/ valRes1__out21;
        QData/*63:0*/ valRes1__en21;
        QData/*63:0*/ valRes1__out22;
        QData/*63:0*/ valRes1__en22;
        QData/*63:0*/ valRes1__out23;
        QData/*63:0*/ valRes1__en23;
        QData/*63:0*/ valRes1__out24;
        QData/*63:0*/ valRes1__en24;
        QData/*63:0*/ valRes1__out25;
        QData/*63:0*/ valRes1__en25;
        QData/*63:0*/ valRes1__out26;
        QData/*63:0*/ valRes1__en26;
        QData/*63:0*/ valRes1__out27;
        QData/*63:0*/ valRes1__en27;
        QData/*63:0*/ valRes1__out28;
        QData/*63:0*/ valRes1__en28;
        QData/*63:0*/ valRes1__out29;
        QData/*63:0*/ valRes1__en29;
        QData/*63:0*/ valRes1__out30;
        QData/*63:0*/ valRes1__en30;
        QData/*63:0*/ valRes1__out31;
        QData/*63:0*/ valRes1__en31;
        QData/*63:0*/ valRes1__out32;
        QData/*63:0*/ valRes1__en32;
        QData/*63:0*/ valRes1__out33;
        QData/*63:0*/ valRes1__en33;
        QData/*63:0*/ valRes1__out34;
        QData/*63:0*/ valRes1__en34;
        QData/*63:0*/ valRes1__out35;
        QData/*63:0*/ valRes1__en35;
        QData/*63:0*/ valRes1__out36;
        QData/*63:0*/ valRes1__en36;
        QData/*63:0*/ valRes1__out37;
        QData/*63:0*/ valRes1__en37;
        QData/*63:0*/ valRes1__out38;
        QData/*63:0*/ valRes1__en38;
        QData/*63:0*/ valRes1__out39;
        QData/*63:0*/ valRes1__en39;
        QData/*63:0*/ valRes1__out40;
        QData/*63:0*/ valRes1__en40;
        QData/*63:0*/ valRes1__out41;
        QData/*63:0*/ valRes1__en41;
        QData/*63:0*/ valRes1__out42;
        QData/*63:0*/ valRes1__en42;
        QData/*63:0*/ valRes1__out43;
        QData/*63:0*/ valRes1__en43;
        QData/*63:0*/ valRes1__out44;
        QData/*63:0*/ valRes1__en44;
        QData/*63:0*/ valRes1__out45;
        QData/*63:0*/ valRes1__en45;
        QData/*63:0*/ valRes1__out46;
        QData/*63:0*/ valRes1__en46;
        QData/*63:0*/ valRes1__out47;
        QData/*63:0*/ valRes1__en47;
        QData/*63:0*/ valRes1__out48;
        QData/*63:0*/ valRes1__en48;
        QData/*63:0*/ valRes1__out49;
        QData/*63:0*/ valRes1__en49;
        QData/*63:0*/ valRes1__out50;
        QData/*63:0*/ valRes1__en50;
        QData/*63:0*/ valRes1__out51;
        QData/*63:0*/ valRes1__en51;
    };
    struct {
        QData/*63:0*/ valRes2__en55;
        QData/*63:0*/ valRes2__out56;
        QData/*63:0*/ valRes2__en56;
        QData/*63:0*/ valRes2__out57;
        QData/*63:0*/ valRes2__en57;
    };
    
    // INTERNAL VARIABLES
  private:
    Vfu_alu__Syms* __VlSymsp;  // Symbol table
  public:
    
    // PARAMETERS
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vfu_alu_alu);  ///< Copying not allowed
  public:
    Vfu_alu_alu(const char* name = "TOP");
    ~Vfu_alu_alu();
    
    // API METHODS
    
    // INTERNAL METHODS
    void __Vconfigure(Vfu_alu__Syms* symsp, bool first);
    void _combo__TOP__fu_alu__DOT__alu4__19(Vfu_alu__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _sequent__TOP__fu_alu__DOT__alu0__14(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu0__7(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu1__17(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu1__8(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu2__13(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu2__9(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu3__10(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu3__16(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu4__11(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu4__15(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu5__12(Vfu_alu__Syms* __restrict vlSymsp);
    void _sequent__TOP__fu_alu__DOT__alu5__18(Vfu_alu__Syms* __restrict vlSymsp);
    void _settle__TOP__fu_alu__DOT__alu0__1(Vfu_alu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__fu_alu__DOT__alu1__3(Vfu_alu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__fu_alu__DOT__alu2__2(Vfu_alu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__fu_alu__DOT__alu3__4(Vfu_alu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__fu_alu__DOT__alu4__6(Vfu_alu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__fu_alu__DOT__alu5__5(Vfu_alu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(128);

#endif // guard
