
enum {KW_NONE,KW_LINKAGE,KW_FNCALL,KW_VIS,KW_VARTYPE,KW_DLLSYM,
  KW_THR,KW_THRMODEL,KW_TYPE,KW_TYPE_NOSZ,KW_PHI,KW_OPER,KW_DECL};
enum {KW_LNK_EXT,KW_LNK_PRIVATE,KW_LNK_INTERNAL,KW_LNK_AVAIL_EXT,
  KW_LNK_LINKONCE,KW_LNK_WEAK,KW_LNK_COMMON,KW_LNK_APPENDING,
  KW_LNK_EWEAK,KW_LNK_WEAK_ODR,KW_LNK_LINKONCE_ODR,

  KW_FN_CCC,KW_FN_FASTCC,KW_FN_COLDCC,KW_FN_WEBKIT,KW_FN_ANYREGCC,
  KW_FN_PRES_MOSTCC,KW_FN_PRES_ALLCC,KW_FN_TLSCC,KW_FN_SWIFTCC,KW_FN_CC,
  KW_VIS_DEF,KW_VIS_HIDDEN,KW_VIS_PROT,

  KW_VAR_CONST,KW_VAR_GLOBAL,KW_VAR_TYPE,

  KW_DLL_IMPORT,KW_DLL_EXPORT,
  KW_THR_THREAD,KW_THRM_LOCDYN,KW_THRM_INIEXE,KW_THRM_LOCEXE,
  KW_TYP_HALF,KW_TYP_FPS,KW_TYP_FPD,KW_TYP_FPE,KW_TYP_VOID,KW_TYP_TOKEN,KW_TYP_LABEL,KW_TYP_META,KW_TYP_VARARG,
  KW_PHI_PHI,
//UNIMPLEMENTED
  KW_OP_ADD,KW_OP_FADD,KW_OP_SUB,KW_OP_FSUB,KW_OP_MUL,KW_OP_FMUL,KW_OP_UDIV,
  KW_OP_SDIV,KW_OP_FDIV,KW_OP_UREM,KW_OP_SREM,KW_OP_FREM,KW_OP_SHL,KW_OP_LSHR,
  KW_OP_ASHR,KW_OP_AND,KW_OP_OR,KW_OP_XOR,KW_DECLARE,KW_DEFINE
};

struct _init_KW {
  char name[32];
  int type;
  int number;
} init_KW[]={
{ "private",KW_LINKAGE,KW_LNK_PRIVATE},
{ "internal",KW_LINKAGE,KW_LNK_INTERNAL},
{ "available_externally",KW_LINKAGE,KW_LNK_AVAIL_EXT},
{ "linkonce",KW_LINKAGE,KW_LNK_LINKONCE},
{ "weak",KW_LINKAGE,KW_LNK_WEAK},
{ "common",KW_LINKAGE,KW_LNK_COMMON},
{ "appending",KW_LINKAGE,KW_LNK_APPENDING},
{ "extern_weak",KW_LINKAGE,KW_LNK_EWEAK},
{ "linkonce_odr",KW_LINKAGE,KW_LNK_LINKONCE_ODR},
{ "weak_odr",KW_LINKAGE,KW_LNK_WEAK_ODR},
{ "external",KW_LINKAGE,KW_LNK_EXT},

{ "ccc",KW_LINKAGE,KW_FN_CCC},
{ "fastcc",KW_LINKAGE,KW_FN_FASTCC},
{ "coldcc",KW_LINKAGE,KW_FN_COLDCC},
{ "webkit_jscc",KW_LINKAGE,KW_FN_WEBKIT},
{ "anyregcc",KW_LINKAGE,KW_FN_ANYREGCC},
{ "preserve_mostcc",KW_LINKAGE,KW_FN_PRES_MOSTCC},
{ "preserve_allcc",KW_LINKAGE,KW_FN_PRES_ALLCC},
{ "cxx_fast_tlscc",KW_LINKAGE,KW_FN_TLSCC},
{ "swiftcc",KW_LINKAGE,KW_FN_SWIFTCC},
{ "cc",KW_LINKAGE,KW_FN_CC},

{ "default",KW_LINKAGE,KW_VIS_DEF},
{ "hidden",KW_LINKAGE,KW_VIS_HIDDEN},
{ "protected",KW_LINKAGE,KW_VIS_PROT},

{ "global",KW_VARTYPE,KW_VAR_GLOBAL},
{ "constant",KW_VARTYPE,KW_VAR_CONST},
{ "type",KW_VARTYPE,KW_VAR_TYPE},

{ "dllimport",KW_DLLSYM,KW_DLL_IMPORT},
{ "dllexport",KW_DLLSYM,KW_DLL_EXPORT},

{ "thread_local",KW_THR,KW_THR_THREAD},
{ "localdynamic",KW_THRMODEL,KW_THRM_LOCDYN},
{ "initialexec",KW_THRMODEL,KW_THRM_INIEXE},
{ "localexec",KW_THRMODEL,KW_THRM_LOCEXE},
{ "half",KW_TYPE,KW_TYP_HALF},
{ "single",KW_TYPE,KW_TYP_FPS},
{ "double",KW_TYPE,KW_TYP_FPD},
{ "x86_fp80",KW_TYPE,KW_TYP_FPE},
{ "void",KW_TYPE_NOSZ,KW_TYP_VOID},
{ "token",KW_TYPE,KW_TYP_TOKEN},
{ "label",KW_TYPE,KW_TYP_LABEL},
{ "meta",KW_TYPE_NOSZ,KW_TYP_META},
{ "phi",KW_PHI,KW_PHI_PHI},
{ "add",KW_OPER,KW_OP_ADD},
{ "fadd",KW_OPER,KW_OP_FADD},
{ "sub",KW_OPER,KW_OP_SUB},
{ "fsub",KW_OPER,KW_OP_FSUB},
{ "mul",KW_OPER,KW_OP_MUL},
{ "fmul",KW_OPER,KW_OP_FMUL},
{ "udiv",KW_OPER,KW_OP_UDIV},
{ "sdiv",KW_OPER,KW_OP_SDIV},
{ "fdiv",KW_OPER,KW_OP_FDIV},
{ "urem",KW_OPER,KW_OP_UREM},
{ "srem",KW_OPER,KW_OP_SREM},
{ "frem",KW_OPER,KW_OP_FREM},
{ "shl",KW_OPER,KW_OP_SHL},
{ "lshr",KW_OPER,KW_OP_LSHR},
{ "ashr",KW_OPER,KW_OP_ASHR},
{ "and",KW_OPER,KW_OP_AND},
{ "or",KW_OPER,KW_OP_OR},
{ "xor",KW_OPER,KW_OP_XOR},
{ "declare",KW_DECL,KW_DECLARE},
{ "define",KW_DECL,KW_DEFINE},
{"",0,0}
};
