enum {KW_NONE,KW_LINKAGE,KW_FNCALL,KW_VIS,KW_VARTYPE,KW_DLLSYM,
  KW_THR,KW_THRMODEL,KW_TYPE,KW_TYPE_NOSZ,KW_PHI,KW_OPER};
enum {KW_LNK_EXT,KW_LNK_PRIVATE,KW_LNK_INTERNAL,KW_LNK_AVAIL_EXT,
  KW_LNK_LINKONCE,KW_LNK_WEAK,KW_LNK_COMMON,KW_LNK_APPENDING,
  KW_LNK_EWEAK,KW_LNK_WEAK_ODR,KW_LNK_LINKONCE_ODR,

  KW_FN_CCC,KW_FN_FASTCC,KW_FN_COLDCC,KW_FN_WEBKIT,KW_FN_ANYREGCC,
  KW_FN_PRES_MOSTCC,KW_FN_PRES_ALLCC,KW_FN_TLSCC,KW_FN_SWIFTCC,KW_FN_CC,
  KW_VIS_DEF,KW_VIS_HIDDEN,KW_VIS_PROT,

  KW_VAR_CONST,KW_VAR_GLOBAL,KW_VAR_TYPE,

  KW_DLL_IMPORT,KW_DLL_EXPORT,
  KW_THR_THREAD,KW_THRM_LOCDYN,KW_THRM_INIEXE,KW_THRM_LOCEXE,
  KW_TYP_HALF,KW_TYP_FPS,KW_TYP_FPD,KW_TYP_FPE,KW_TYP_VOID,KW_TYP_TOKEN,KW_TYP_LABEL,KW_TYP_META,KW_TYP_VARARG,
  KW_PHI_PHI,
//UNIMPLEMENTED
  KW_OP_ADD,KW_OP_FADD,KW_OP_SUB,KW_OP_FSUB,KW_OP_MUL,KW_OP_FMUL,KW_OP_UDIV,
  KW_OP_SDIV,KW_OP_FDIV,KW_OP_UREM,KW_OP_SREM,KW_OP_FREM,KW_OP_SHL,KW_OP_LSHR,
  KW_OP_ASHR,KW_OP_AND,KW_OP_OR,KW_OP_XOR,
};



struct _init_KW {
  char name[32];
  int type;
  int number;
} init_KW[];
